baseurl = "https://edmundgoodman.github.io"
title = "Edmund Goodman"
languageCode = "en-gb"

# Theme to use
theme = "minimal-theme"
enableEmoji = true

# Allow raw html (required for markdown comments)
# <https://discourse.gohugo.io/t/ignorelogs-warning-goldmark-raw-html/52469/2>
ignoreLogs = ["warning-goldmark-raw-html"]

# Pagination
[pagination]
pagerSize = 7
path = "page"

# Highlighting
[markup]
  # <https://gohugo.io/getting-started/configuration-markup/#highlight>
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    lineNos = true
    lineNumbersInTable = false

# Taxonomies
# [taxonomies]
# tag = "tags"
# category = "categories"

# Menu
[menu]
# Header
[[menu.main]]
url = "/about"
name = "About"
weight = 1
[[menu.main]]
url = "/posts/"
name = "Blog"
weight = 2
# Footer (hijacked to make the atlas page work)
[[menu.footer]]
url = "atlas/"
name = "Atlas"
weight = 1
# [[menu.footer]]
# url = "gelato/"
# name = "Gelato"
# weight = 2

# Links format
[permalinks]
posts = "/posts/:year/:title/"
gelato = "/gelato/:year/:month/:day/"

# Meta
[params]
author = "Edmund Goodman"
email = "hello@edmundgoodman.co.uk"
description = "The personal website for Edmund Goodman"

[params.home]
subtitles = ["Computer Scientist", "University of Cambridge"]

[params.footer]
repository_url = "https://github.com/EdmundGoodman/edmundgoodman.github.io"
license_url = "https://creativecommons.org/licenses/by-nc/4.0/"

[[params.social]]
name = "GitHub"
url = "https://github.com/EdmundGoodman"

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/edmundgoodman/"
