baseurl = "https://edmundgoodman.github.io"
title = "Edmund Goodman"
languageCode = "en-uk"

# Theme to use
theme = "simple-theme"
enableEmoji = true

# Pagination
paginate = 7
paginatePath = "page"

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=inline"
pygmentsStyle = "monokai"


# Taxonomies
# [taxonomies]
# tag = "tags"
# category = "categories"


# Menu
[menu]
# Header
[[menu.main]]
url = "/about"
name = "About"
weight = 1
[[menu.main]]
url = "/projects/"
name = "Projects"
weight = 2
[[menu.main]]
url = "/posts/"
name = "Blog"
weight = 3


# Links format
[permalinks]
posts = "/posts/:year/:month/:title/"


# Meta
[params]
author = "Edmund Goodman"
author_url = "https://github.com/EdmundGoodman"
author_image = "/images/france_photo_squared.jpg"
license = "CC BY-NC 4.0"
license_url = "https://creativecommons.org/licenses/by-nc/4.0/"
description = "The personal website for Edmund Goodman"

[params.home]
subtitles = ["Computer Scientist", "University of Warwick"]

[params.footer]
author = true
license = true

[[params.social]]
name = "github"
icon = "bi bi-github"
url = "https://github.com/EdmundGoodman"

[[params.social]]
name = "linkedin"
icon = "bi bi-linkedin"
url = "https://www.linkedin.com/in/edmundgoodman/"
