baseurl = "https://edmundgoodman.co.uk"
title = "Edmund Goodman"
languageCode = "en-gb"

# Theme to use
theme = "minimal-theme"
enableEmoji = true

# Pagination
[pagination]
pagerSize = 7
path = "page"

# Highlighting
[markup]
  # <https://gohugo.io/getting-started/configuration-markup/#highlight>
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    lineNos = true
    lineNumbersInTable = false

  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

# Taxonomies
# [taxonomies]
# tag = "tags"
# category = "categories"

# Menu
[menu]
# Header
[[menu.main]]
url = "about/"
name = "About"
weight = 1
[[menu.main]]
url = "posts/"
name = "Blog"
weight = 2
[[menu.main]]
url = "atlas/"
name = "Atlas"
weight = 3
# Footer (hijacked to make the atlas page work)
# [[menu.footer]]
# url = "gelato/"
# name = "Gelato"
# weight = 2

# Links format
[permalinks]
posts = "/posts/:year/:title/"
gelato = "/gelato/:year/:month/:day/"

# Meta
[params]
author = "Edmund Goodman"
email = "hello@edmundgoodman.co.uk"
description = "The personal website for Edmund Goodman"
math = false

[params.home]
subtitles = ["Computer Scientist", "University of Cambridge"]

[params.footer]
repository_url = "https://github.com/EdmundGoodman/edmundgoodman.github.io"
license_url = "https://creativecommons.org/licenses/by-nc/4.0/"

[[params.social]]
name = "GitHub"
url = "https://github.com/EdmundGoodman"

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/edmundgoodman/"
