baseurl = "https://edmundgoodman.github.io"
title = "Edmund Goodman"
languageCode = "en-gb"

# Theme to use
theme = "simple-theme"
enableEmoji = true

# Pagination
[pagination]
pagerSize = 7
path = "page"

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=inline"
pygmentsStyle = "monokai"

# Taxonomies
# [taxonomies]
# tag = "tags"
# category = "categories"


# Menu
[menu]
# Header
[[menu.main]]
url = "/about"
name = "About"
weight = 1
[[menu.main]]
url = "/posts/"
name = "Blog"
weight = 2


# Links format
[permalinks]
posts = "/posts/:year/:month/:title/"


# Meta
[params]
author = "Edmund Goodman"
subtitle = "Computer Scientist"
description = "The personal website for Edmund Goodman"

[[params.footer]]
repository = "https://github.com/EdmundGoodman/edmundgoodman.github.io"
license = "CC BY-NC 4.0"
license_url = "https://creativecommons.org/licenses/by-nc/4.0/"

[[params.social]]
name = "github"
icon = "bi bi-github"
url = "https://github.com/EdmundGoodman"

[[params.social]]
name = "linkedin"
icon = "bi bi-linkedin"
url = "https://www.linkedin.com/in/edmundgoodman/"
