name: Scrape Gelato menu

on:
  workflow_dispatch:
  schedule:
    - cron: 15 10 * * *

permissions:
  contents: write

jobs:
  get-menu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: |
          cd scripts/gelato
          make run
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add new Jack's Gelato menu"
