name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  workflow_dispatch:
  schedule:
    - cron: 25 10 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Include up-to-date menus
        run: |
          cd artifacts/jacks-menu-history
          git checkout main
          git pull
          rm ../../content/gelato
          mv markdown ../../content/gelato

      - name: Build site with Hugo
        run: |
          hugo --minify
          cp ./CNAME ./public/CNAME

      - name: Deploy site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#%EF%B8%8F-set-git-username-and-email
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
